name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Versão do Node.js compatível com PNPM
          cache: 'pnpm'

      # Instalar e ativar o PNPM
      - name: Install and Activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Verificar versão do PNPM
      - name: Verify pnpm version
        run: pnpm --version

      # Instalar dependências com PNPM
      - name: Install dependencies
        run: pnpm install

      # Executar os testes no modo headless
      - name: Run Cypress Tests
        run: pnpm exec cypress run --browser chrome --headless

      # Salvar artefatos (vídeos e capturas de tela)
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
