name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Instalar o pnpm manualmente e adicioná-lo ao PATH
      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "::add-path::$(npm bin -g)" # Adiciona o binário do pnpm ao PATH

      # Verificar a versão do pnpm
      - name: Verify pnpm version
        run: pnpm --version

      # Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # Executar os testes no modo headless
      - name: Run Cypress Tests
        run: pnpm exec cypress run --browser chrome --headless

      # Salvar artefatos (vídeos e capturas de tela)
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/



